mod_name = "AllFours"
mod_id = "all_fours"
mod_group = "com.theendercore"
mod_version = "1.0.0"
mod_description = "Simple crwaling and sitting mod"
github_repo = "theendercore/AllFours"
discord_invite = "https://discord.gg/KZ5Q364hEg"
authors = [ "TheEnderCore" ]
license = "MIT"
version_range = ">=1.21.11 <26.1"
